export const menuData = [
  {
    id: "1",
    name: "Margherita Pizza",
    description: "Classic pizza with fresh mozzarella, basil, and tomato sauce",
    price: 12.99,
    category: "Pizza",
    image: "/margherita-pizza.png",
    rating: 4.8,
  },
  {
    id: "2",
    name: "Pepperoni Pizza",
    description: "Delicious pizza topped with pepperoni and mozzarella cheese",
    price: 13.99,
    category: "Pizza",
    image: "/pepperoni-pizza.png",
    rating: 4.7,
  },
  {
    id: "3",
    name: "Vegetarian Pizza",
    description: "Fresh vegetables on a crispy pizza crust",
    price: 11.99,
    category: "Pizza",
    image: "/vegetarian-pizza.jpg",
    rating: 4.6,
  },
  {
    id: "4",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    price: 10.99,
    category: "Burgers",
    image: "/classic-burger.png",
    rating: 4.5,
  },
  {
    id: "5",
    name: "Chicken Burger",
    description: "Crispy fried chicken with coleslaw and mayo",
    price: 9.99,
    category: "Burgers",
    image: "/delicious-chicken-burger.png",
    rating: 4.6,
  },
  {
    id: "6",
    name: "Bacon Cheeseburger",
    description: "Beef patty with crispy bacon and melted cheddar",
    price: 11.99,
    category: "Burgers",
    image: "/bacon-cheeseburger.png",
    rating: 4.7,
  },
  {
    id: "7",
    name: "Grilled Salmon",
    description: "Fresh grilled salmon with lemon butter sauce",
    price: 18.99,
    category: "Seafood",
    image: "/grilled-salmon-plate.png",
    rating: 4.9,
  },
  {
    id: "8",
    name: "Shrimp Pasta",
    description: "Succulent shrimp in garlic white wine sauce",
    price: 16.99,
    category: "Seafood",
    image: "/shrimp-pasta.png",
    rating: 4.8,
  },
  {
    id: "9",
    name: "Fish and Chips",
    description: "Crispy battered fish with golden fries",
    price: 14.99,
    category: "Seafood",
    image: "/classic-fish-and-chips.png",
    rating: 4.5,
  },
  {
    id: "10",
    name: "Caesar Salad",
    description: "Crisp romaine with parmesan and croutons",
    price: 8.99,
    category: "Salads",
    image: "/caesar-salad.png",
    rating: 4.4,
  },
  {
    id: "11",
    name: "Greek Salad",
    description: "Fresh vegetables with feta cheese and olives",
    price: 9.99,
    category: "Salads",
    image: "/greek-salad.png",
    rating: 4.6,
  },
  {
    id: "12",
    name: "Buddha Bowl",
    description: "Vegan bowl with quinoa, vegetables, and tahini dressing",
    price: 10.99,
    category: "Salads",
    image: "/vegan-buddha-bowl.png",
    rating: 4.7,
  },
  {
    id: "13",
    name: "Tiramisu",
    description: "Classic Italian dessert with mascarpone and cocoa",
    price: 6.99,
    category: "Desserts",
    image: "/classic-tiramisu.png",
    rating: 4.8,
  },
  {
    id: "14",
    name: "Chocolate Cake",
    description: "Rich and decadent chocolate cake with frosting",
    price: 7.99,
    category: "Desserts",
    image: "/decadent-chocolate-cake.png",
    rating: 4.9,
  },
  {
    id: "15",
    name: "Cheesecake",
    description: "Creamy New York style cheesecake",
    price: 7.99,
    category: "Desserts",
    image: "/classic-cheesecake.png",
    rating: 4.7,
  },
]
